"""Initial migration

Revision ID: 54f6379425e5
Revises:
Create Date: 2018-01-06 22:17:20.953599
"""
from alembic import op
import sqlalchemy as sa
import elixr2.data.db.types


# revision identifiers, used by Alembic.
revision = '54f6379425e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_activations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('uuid', elixr2.data.db.types.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_activations')),
    sa.UniqueConstraint('code', name=op.f('uq_auth_activations_code')),
    sa.UniqueConstraint('uuid', name=op.f('uq_auth_activations_uuid'))
    )
    op.create_table('auth_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(create_constraint=False), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('uuid', elixr2.data.db.types.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_auth_roles_name')),
    sa.UniqueConstraint('uuid', name=op.f('uq_auth_roles_uuid'))
    )
    op.create_table('auth_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(create_constraint=False), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=20), nullable=True),
    sa.Column('registration_source', sa.String(length=100), nullable=True),
    sa.Column('first_login', sa.DateTime(), nullable=True),
    sa.Column('activation_id', elixr2.data.db.types.UUID(), nullable=True),
    sa.Column('uuid', elixr2.data.db.types.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['activation_id'], ['auth_activations.uuid'], name=op.f('fk_auth_users_activation_id_auth_activations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_users')),
    sa.UniqueConstraint('email', name=op.f('uq_auth_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_auth_users_username')),
    sa.UniqueConstraint('uuid', name=op.f('uq_auth_users_uuid'))
    )
    op.create_table('auth_userroles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', elixr2.data.db.types.UUID(), nullable=True),
    sa.Column('role_id', elixr2.data.db.types.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['auth_roles.uuid'], name=op.f('fk_auth_userroles_role_id_auth_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.uuid'], name=op.f('fk_auth_userroles_user_id_auth_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_userroles'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_userroles')
    op.drop_table('auth_users')
    op.drop_table('auth_roles')
    op.drop_table('auth_activations')
    # ### end Alembic commands ###
